apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: osvaldao-rs
  labels:
    app: osvaldao
spec:
  replicas: 6
  selector:
    matchLabels:
      app: osvaldao
  template:
    metadata:
      labels:
        app: osvaldao
    spec:
      containers:
      - name: osvaldao-app
        image: ovaldoy/hello-world-python:0.0.2.RELEASE
